### ISSUE TITLE
Changing title font in Colour Scale Bar

### ISSUE THREAD

**Issue by cratcliff** [BC-Consulting/geoprocalgos#2]
I'm trying to use your _Colour bar for one-band rasters_ however I would like to change the font, weight and size of the title.

I have seen on your [web page](https://www.geoproc.com/be/bccbar3.htm#FP) on how to construct the font properties, and I have started with your example of `{'title_font_properties':{'family':'venetia,sans-serif', 'size':40, 'weight':'ultralight'}}` but when I copy and paste this as an additional parameter and run the tool I get 
```
Input parameters:
{ 'BORDER_COLOR' : 'black', 'BORDER_LW' : 0.8, 'BREVERSED' : False, 'CBWH' : 0.2, 'DECI' : 0, 'DIVIDER_COLOR' : 'black', 'DIVIDER_LW' : 0, 'FONT_SIZE' : 6, 'LABEL_ALT' : False, 'LABEL_BOTH' : False, 'LABEL_ON' : 0, 'OFFSET' : 0, 'ORI' : 1, 'OUTPUT' : 'C:/_Projects/Frosts/SA_Karoonda_Lollers_Primrose/project_data/Analysis/Terrain/elev_legend.html', 'TFONT' : 0, 'THE_LAYER' : 'C:/_Projects/Frosts/SA_Karoonda_Lollers_Primrose/project_data/Analysis/Terrain/elev.tif', 'TICKSEP' : 50, 'TITLE' : 'Elevation (m Above Sea Level)', 'TITLE_COLOR' : 'black', 'UFONT' : 1, 'UNITS' : '', 'UNITS_COLOR' : 'black', 'WITH_PNG' : False, 'XTRA_PARAM' : '{\'title_font_properties\':{\'family\':\'venetia,sans-serif\', \'size\':40, \'weight\':\'ultralight\'}}' }

Traceback (most recent call last):
File "C:/Users/rat062/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\bcCBar_algorithm.py", line 442, in processAlgorithm
output_file = self._continue_proc(mycb, ori, labboth, labalt, output_file)
File "C:/Users/rat062/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\bcCBar_algorithm.py", line 243, in _continue_proc
mycb.set_extras(self.xtrap)
File "C:/Users/rat062/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\CBar3.py", line 938, in set_extras
self.title_font_properties = self._check_font_properties(L)
File "C:/Users/rat062/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\CBar3.py", line 327, in _check_font_properties
font = self._get_dict(font0)
File "C:/Users/rat062/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\CBar3.py", line 446, in _get_dict
return {kv.split(':')[0]:kv.split(':')[1] for kv in q if kv != ''}
File "C:/Users/rat062/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\CBar3.py", line 446, in <dictcomp>
return {kv.split(':')[0]:kv.split(':')[1] for kv in q if kv != ''}
IndexError: list index out of range

Execution failed after 0.11 seconds
```
What am I doing wrong?

**Comment by BC-Consulting** [comment]
Hello Christina,

Very sorry for the long delay in replying!

The issue you had should now be resolved.
But note that after further testing I can only manage to set the font name and/or its size. The other four properties (variant, stretch, style and weight) cannot be set.

Please have a try: Version 3.13 on github and in the repo.

Regards,
Benoit
