### ISSUE TITLE
QGIS Error: Dependencies not installed

### ISSUE THREAD

**Issue by Watto81** [BC-Consulting/geoprocalgos#4]
Hi Benoit,

I have installed the required dependencies for bcCBar4 however I am receiving the following error message from QGIS.  Are you able to replicate this error and correct it at all?

<img width="714" alt="image" src="https://user-images.githubusercontent.com/123346985/213969429-8ea33344-a5cb-4897-a4b7-c616e844b970.png">

Many thanks

**Comment by BC-Consulting** [comment]
Hi Watto81,
Thanks for reporting your problem.
May I ask you to provide operating system you are on?
On my side I cannot replicate the problem, but it does not mean it is not there...
Thanks,
Benoit

**Comment by Watto81** [comment]
Windows 10
Python 3.11.1
QGIS 3.28.2

**Comment by BC-Consulting** [comment]
Sorry for very late reply. I've upload a new version (V3.30) a while ago that checks for dependencies and load them if necessary. Please, would you mind checking it?

**Comment by AlisterH** [comment]
> Sorry for very late reply. I've upload a new version (V3.30) a while ago that checks for dependencies and load them if necessary. Please, would you mind checking it?

It seems that dependencies aren't all checked for and installed; I have to manually install beautifulsoup (I used pip, before realising there is a package available in osgeo4w), otherwise I get this:
````
Couldn't load plugin 'geoprocalgos' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'bs4' 
Traceback (most recent call last):
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python/plugins\geoprocalgos\cbar\__init__.py", line 50, in 
    from bs4 import BeautifulSoup, __version__ as bs4_version
  File "D:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'bs4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python/plugins\geoprocalgos\__init__.py", line 38, in classFactory
    from .GeoProcAlgos import PPlugins
  File "D:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python/plugins\geoprocalgos\GeoProcAlgos.py", line 40, in 
    from .GeoProc_provider import geoprocProvider
  File "D:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python/plugins\geoprocalgos\GeoProc_provider.py", line 34, in 
    from .bcCBar_algorithm             import bcCBarAlgorithm
  File "D:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python/plugins\geoprocalgos\bcCBar_algorithm.py", line 42, in 
    from .cbar import drawCBar, cbar_usage
  File "D:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python/plugins\geoprocalgos\cbar\__init__.py", line 57, in 
    from bs4 import BeautifulSoup, __version__ as bs4_version
  File "D:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'bs4'


Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.36.1-Maidenhead Maidenhead, 3e589453 

Python Path:
D:/OSGeo4W/apps/qgis/./python
C:/Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python
C:/Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python/plugins
D:/OSGeo4W/apps/qgis/./python/plugins
D:\OSGeo4W\apps\grass\grass83\etc\python
D:\Alister\Documents
D:\OSGeo4W\bin\python312.zip
D:\OSGeo4W\apps\Python312\DLLs
D:\OSGeo4W\apps\Python312\Lib
D:\OSGeo4W\bin
D:\OSGeo4W\apps\Python312
D:\OSGeo4W\apps\Python312\Lib\site-packages
D:\OSGeo4W\apps\Python312\Lib\site-packages\win32
D:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
D:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\temp5/python
